version: "3.1"

services:
  # Serviço que irá rodar o node
  app-redway-email:
    # Imagem base do container
    build: ./back_end
    user: node
    # Nome do container para facilitar execução
    container_name: redway_api
    # Mesmo que `docker run -t`
    tty: true
    # Mesmo que `docker run -i`
    stdin_open: true
    depends_on:
      # Precisa do banco funcionando antes de subir o node
      - db
    ports:
      # Expõe a porta padrão da aplicação:
      - 3001:3001
    # Configura as variáveis de ambiente dentro do container
    environment:
      DB_USER: root
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: RedwayEmails

  # Serviço que irá rodar o banco de dados
  db:
    container_name: redway_emails_db
    image: mysql:8.0.32
    restart: always
    ports:
      # Expõe a porta padrão do banco de dados
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password

  # Serviço que irá rodar o front-end
  front_end:
    container_name: redway_front
    build: ./front_end
    # Mesmo que `docker run -t`
    tty: true
    # Mesmo que `docker run -i`
    stdin_open: true
    ports:
      - 3000:3000
    depends_on:
      - app-redway-email